### ISSUE TITLE
【已解决】NK-MOT1.20.60下报错问题反馈

### ISSUE THREAD

**Issue by lthuas** [Nissining/MusicPlus#5]
作者您好，我在minebbs下载的音乐插件，使用NK-MOT1.20.60（最新版本）核心开服时，遇到了一个报错可以帮我看一下是什么问题吗，/pl的时候音乐插件是绿的，但指令不显示/rmp（未知指令）没办法使用owo
![1709977127790](https://github.com/Nissining/MusicPlus/assets/99377251/36a485d8-cab9-4a95-8df7-20b5e23a5cf1)

**Comment by lthuas** [comment]
使用的NK-MOT核心https://ci.lanink.cn/view/Nukkit/
![1709978028077](https://github.com/Nissining/MusicPlus/assets/99377251/63cf2485-6530-4669-95b9-fee4ee86babc)

**Comment by lthuas** [comment]
使用的NK-MOT核心：https://ci.lanink.cn/view/Nukkit/
![image](https://github.com/Nissining/MusicPlus/assets/99377251/b876cfac-0108-492a-a551-fc857c704842)

**Comment by lthuas** [comment]
使用的NK-MOT核心：https://ci.lanink.cn/view/Nukkit/
![1709978028077](https://github.com/Nissining/MusicPlus/assets/99377251/96323c62-bc70-4f7b-a398-32dc016ebc7d)

**Comment by Nissining** [comment]
using: /mplus help

**Comment by lthuas** [comment]
> using: /mplus help

感谢作者的回复，目前报错和指令问题都已经得到解决
