### ISSUE TITLE
歌曲列表浮空字闪影反馈

### ISSUE THREAD

**Issue by lthuas** [Nissining/MusicPlus#6]
作者晚上好，我设置歌曲列表浮空字后，浮空字会不停的出现闪影，停止和开启音乐状态下都会出现，不知道有没有优化方案ouo

https://github.com/Nissining/MusicPlus/assets/99377251/0f80e84d-0229-4cd3-9921-3ec97f2cf9ac

**Comment by Nissining** [comment]
目前暂时没有更好的解决方案，如果可以Fork本源码自行修改
